/* Do not remove the headers from this file! see /USAGE for more info. */

#ifndef __DAEMONS_H__
#define __DAEMONS_H__

#define ALIAS_D         "/daemons/alias_d"
#define ANNOTATION_D    "/daemons/annotation_d"
#define BANISH_D        "/daemons/banish_d"
#define CHANLOG_D       "/daemons/chanlog_d"
#define CHANNEL_D       "/daemons/channel_d"
#define DID_D           "/daemons/did_d"
#define DOC_D           "/daemons/doc_d"
#define GROUP_D         "/daemons/group_d"
#define GUILD_D         "/daemons/guild_d"
#define HELP_D          "/daemons/help_d"
#define IMUD_D          "/daemons/imud_d"
#define LAST_LOGIN_D    "/daemons/last_login_d"
#define MAILBOX_D       "/daemons/mailbox_d"
#define MESSAGES_D      "/daemons/messages_d"
#define MONEY_D         "/daemons/money_d"
#define NEWS_D          "/daemons/news_d"
#define WEB_D         "/daemons/web_d"
#define MUSEUM_D "/daemons/museum_d"
#define HZK2ASC_D "/daemons/hzk2asc_d"

#define MATH_D        "/daemons/math_d"
#define COLOR_D     "/daemons/color_d"
#define TROOP_TYPE_D  "/daemons/troop_type_d"
#define QUEST_D         "/daemons/quest_d"
#define GINI_D        "/daemons/gini_d"
#define SGHELP_D  "/daemons/sghelp_d"
#define PARASE_D "/daemons/parase_d"
#define JOB_D       "/daemons/job_d"
#define OBJ_D     "/daemons/obj_d"
#define TROOP_D      "/daemons/troop_d"
#define WARAI_D      "/daemons/warai_d"
#define REPORTER_D      "/daemons/reporter_d"
#define SOUL_D          "/daemons/soul_d"
#define BASE_D         "/daemons/base_d"
#define STUFF_D         "/daemons/stuff_d"
#define SPELL_D         "/daemons/spell_d"
#define TIMER_D         "/daemons/timer_d"
#define VERB_D          "/daemons/verb_d"
#define WEATHER_D       "/daemons/weather_d"
#define SKILL_D        "/daemons/skill_d"
#define FIGHT_D        "/daemons/fight_d"
#define VOTE_D  "/daemons/vote_d"
#define SHUTDOWN_D      "/daemons/shutdown_d"
#define CONVERT_D	"/daemons/convert_d"
#define TASK_D      "/daemons/task_d"
#define OFFICER_D     "/daemons/officer_d"
#define AREA_D         "/daemons/area_d"
#define DAY_D         "/daemons/day_d"
#define AI_D       "/daemons/ai_d.lpc"
#define RELATION_D	"/daemons/relation_d.lpc"
#define HP_D           "/daemons/hp_d"
#define MAP_D       "/daemons/map_d.lpc"
#define DELAY_D    "/daemons/delay_d"
#define CMD_D           "/secure/daemons/cmd_d"
#define FINGER_D        "/secure/daemons/finger_d"
#define FTP_D           "/secure/daemons/ftp_d"
#define HTTP_D          "/secure/daemons/http_d"
#define LOG_D           "/secure/daemons/log_d"
#define MAIL_D          "/secure/daemons/mail_d"
#define IMAIL_D         "/secure/daemons/imail_d"
#define NEW_USER_D      "/secure/daemons/new_user_d"
#define SECURE_D        "/secure/daemons/secure_d"
#define USER_D          "/secure/daemons/user_d"
#define CHAR_D         "/daemons/char_d"
#define COUNTRY_D     "/daemons/country_d"
#define LPSCRIPT_D      "/secure/daemons/lpscript_d"

// Define these only if you want intermud services.
#define REMOTE_D        "/secure/daemons/remote"
#define CHANGW_D        "/daemons/changw"

// Chinese manipulation
#define CHINESE_D       "/daemons/chinese_d"
#define DIRECTION_D     "/daemons/direction_d"

#define FATE_D "/daemons/fate_d"
#endif // __DAEMONS_H__
