([ /* sizeof() == 41 */
  "taxnation" : 10,
  "soldier" : 0,
  "agriculture" : 35,
  "troop" : ([ /* sizeof() == 1 */
      "cavalry" : 261,
    ]),
  "st" : ([ ]),
  "weather" : 4,
  "go" : "vzhu_lin",
  "train" : 158,
  "wind" : 5,
  "nation" : "west",
  "importance" : 0,
  "taxlocal" : 28,
  "level" : 2,
  "business" : 40,
  "bn" : ([ ]),
  "safe" : 26,
  "entry" : "vdagu_chang",
  "neighbor" : ({ /* sizeof() == 2 */
      "changan",
      "tongguan"
    }),
  "market" : "vcenter",
  "morale" : 118,
  "bussiness" : 50,
  "n_wind" : 4,
  "gold" : 32253,
  "meeting" : "venter",
  "fly" : "vroad1",
  "att_task" : 0,
  "population" : 1790,
  "base" : 0,
  "map" : 0,
  "ssoldiers" : ([ /* sizeof() == 2 */
      "new" : ([ /* sizeof() == 4 */
          "morale" : 200,
          "time" : 1008397898,
          "troop" : ([ /* sizeof() == 1 */
              "cavalry" : 263,
            ]),
          "train" : 200,
        ]),
      "old" : ([ /* sizeof() == 4 */
          "morale" : 200,
          "time" : 1008396033,
          "troop" : ([ /* sizeof() == 1 */
              "cavalry" : 263,
            ]),
          "train" : 200,
        ]),
    ]),
  "center" : ({ /* sizeof() == 2 */
      8,
      6
    }),
  "status" : 1,
  "last_party_time" : 981516912,
  "area" : 0,
  "bl" : 0,
  "prison" : "hy_lf",
  "name" : "华阴",
  "industry" : 40,
  "path" : "/a/huayin/",
  "n_weather" : 6,
  "zhou" : "雍州",
])
