([ /* sizeof() == 72 */
  12 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 5,
        ]),
      "level" : 3,
      "name" : "校尉",
    ]),
  11 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 4,
        ]),
      "level" : 4,
      "name" : "校尉",
    ]),
  10 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 3,
        ]),
      "level" : 4,
      "name" : "将军",
    ]),
  9 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 2,
        ]),
      "level" : 5,
      "name" : "右将军",
    ]),
  8 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 2,
        ]),
      "level" : 5,
      "name" : "左将军",
    ]),
  7 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 2,
        ]),
      "level" : 5,
      "name" : "后将军",
    ]),
  6 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 2,
        ]),
      "level" : 5,
      "name" : "前将军",
    ]),
  5 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 1,
        ]),
      "level" : 6,
      "name" : "卫将军",
    ]),
  4 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 1,
        ]),
      "level" : 6,
      "name" : "车骑将军",
    ]),
  3 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 1,
        ]),
      "level" : 6,
      "name" : "骠骑将军",
    ]),
  2 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 0,
        ]),
      "level" : 7,
      "name" : "大将军",
    ]),
  1 : ([ /* sizeof() == 3 */
      "num" : 1,
      "level" : 9,
      "name" : "主公",
    ]),
  31 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 1,
          "area_level" : 5,
        ]),
      "level" : 4,
      "name" : "曲将",
    ]),
  30 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 0,
          "area_level" : 5,
        ]),
      "level" : 5,
      "name" : "副将",
    ]),
  22 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 0,
          "typ" : 2,
          "off_lev" : 2,
        ]),
      "level" : 3,
      "name" : "偏将军",
    ]),
  21 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 0,
          "typ" : 2,
          "off_lev" : 1,
        ]),
      "level" : 4,
      "name" : "将军",
    ]),
  20 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 0,
          "typ" : 2,
          "off_lev" : 0,
        ]),
      "level" : 5,
      "name" : "大将军",
    ]),
  43 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 3,
          "area_level" : 4,
        ]),
      "level" : 2,
      "name" : "都尉",
    ]),
  42 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 2,
          "area_level" : 4,
        ]),
      "level" : 3,
      "name" : "督军",
    ]),
  41 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 1,
          "area_level" : 4,
        ]),
      "level" : 4,
      "name" : "监将",
    ]),
  40 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 0,
          "area_level" : 4,
        ]),
      "level" : 5,
      "name" : "部将",
    ]),
  33 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 3,
          "area_level" : 5,
        ]),
      "level" : 2,
      "name" : "校尉",
    ]),
  32 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 2,
          "area_level" : 5,
        ]),
      "level" : 3,
      "name" : "典将",
    ]),
  61 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 1,
          "area_level" : 2,
        ]),
      "level" : 2,
      "name" : "武卫",
    ]),
  60 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 0,
          "area_level" : 2,
        ]),
      "level" : 3,
      "name" : "典军",
    ]),
  52 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 2,
          "area_level" : 3,
        ]),
      "level" : 2,
      "name" : "领军",
    ]),
  51 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 1,
          "area_level" : 3,
        ]),
      "level" : 3,
      "name" : "牙将",
    ]),
  50 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 0,
          "area_level" : 3,
        ]),
      "level" : 4,
      "name" : "裨将",
    ]),
  71 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 1,
          "area_level" : 1,
        ]),
      "level" : 2,
      "name" : "护军",
    ]),
  70 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 2,
          "off_lev" : 0,
          "area_level" : 1,
        ]),
      "level" : 3,
      "name" : "监军",
    ]),
  111 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 2,
        ]),
      "level" : 6,
      "name" : "大理卿",
    ]),
  110 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 2,
        ]),
      "level" : 6,
      "name" : "鸿胪卿",
    ]),
  109 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 2,
        ]),
      "level" : 6,
      "name" : "光禄卿",
    ]),
  108 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 2,
        ]),
      "level" : 6,
      "name" : "司农卿",
    ]),
  107 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 2,
        ]),
      "level" : 6,
      "name" : "太仆卿",
    ]),
  106 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 2,
        ]),
      "level" : 6,
      "name" : "太常卿",
    ]),
  105 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 1,
        ]),
      "level" : 7,
      "name" : "太保",
    ]),
  104 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 1,
        ]),
      "level" : 7,
      "name" : "太师",
    ]),
  102 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 0,
        ]),
      "level" : 8,
      "name" : "大司空",
    ]),
  101 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 0,
        ]),
      "level" : 8,
      "name" : "丞相",
    ]),
  99 : ([ /* sizeof() == 4 */
      "num" : 1,
      "level" : 8,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 2,
          "off_lev" : 1,
        ]),
      "name" : "大司马",
    ]),
  119 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 5,
        ]),
      "level" : 3,
      "name" : "学士",
    ]),
  118 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 4,
        ]),
      "level" : 4,
      "name" : "大学士",
    ]),
  117 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 3,
        ]),
      "level" : 5,
      "name" : "光禄大夫",
    ]),
  116 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 3,
        ]),
      "level" : 5,
      "name" : "秘书监",
    ]),
  115 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 3,
        ]),
      "level" : 5,
      "name" : "尚书令",
    ]),
  114 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 3,
        ]),
      "level" : 5,
      "name" : "中书令",
    ]),
  113 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 3,
        ]),
      "level" : 5,
      "name" : "散骑常侍",
    ]),
  112 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 1,
          "typ" : 1,
          "off_lev" : 3,
        ]),
      "level" : 5,
      "name" : "侍中",
    ]),
  132 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 0,
          "typ" : 1,
          "off_lev" : 2,
        ]),
      "level" : 3,
      "name" : "长史",
    ]),
  131 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 0,
          "typ" : 1,
          "off_lev" : 1,
        ]),
      "level" : 4,
      "name" : "副军师",
    ]),
  130 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "nation",
          "nation_level" : 0,
          "typ" : 1,
          "off_lev" : 0,
        ]),
      "level" : 5,
      "name" : "总军师",
    ]),
  157 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 4,
          "area_level" : 5,
        ]),
      "level" : 2,
      "name" : "功曹",
    ]),
  156 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 3,
          "area_level" : 5,
        ]),
      "level" : 3,
      "name" : "吏曹",
    ]),
  152 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 1,
          "area_level" : 5,
        ]),
      "level" : 5,
      "name" : "参谋",
    ]),
  151 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 0,
          "area_level" : 5,
        ]),
      "level" : 6,
      "name" : "军师",
    ]),
  150 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 0,
          "off_lev" : 0,
          "area_level" : 5,
        ]),
      "level" : 6,
      "name" : "太守",
    ]),
  173 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 2,
          "area_level" : 3,
        ]),
      "level" : 2,
      "name" : "议曹",
    ]),
  172 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 1,
          "area_level" : 3,
        ]),
      "level" : 3,
      "name" : "从事",
    ]),
  171 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 0,
          "area_level" : 3,
        ]),
      "level" : 4,
      "name" : "别驾",
    ]),
  170 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 0,
          "off_lev" : 0,
          "area_level" : 3,
        ]),
      "level" : 4,
      "name" : "镇太守",
    ]),
  166 : ([ /* sizeof() == 4 */
      "num" : 7,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 3,
          "area_level" : 4,
        ]),
      "level" : 2,
      "name" : "决曹",
    ]),
  165 : ([ /* sizeof() == 4 */
      "num" : 5,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 2,
          "area_level" : 4,
        ]),
      "level" : 3,
      "name" : "治中",
    ]),
  161 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 0,
          "area_level" : 4,
        ]),
      "level" : 5,
      "name" : "主簿",
    ]),
  160 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 0,
          "off_lev" : 0,
          "area_level" : 4,
        ]),
      "level" : 5,
      "name" : "郡太守",
    ]),
  191 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 0,
          "area_level" : 1,
        ]),
      "level" : 3,
      "name" : "参军",
    ]),
  190 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 0,
          "off_lev" : 0,
          "area_level" : 1,
        ]),
      "level" : 3,
      "name" : "主将",
    ]),
  182 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 1,
          "area_level" : 2,
        ]),
      "level" : 2,
      "name" : "通事",
    ]),
  181 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 0,
          "area_level" : 2,
        ]),
      "level" : 3,
      "name" : "书爷",
    ]),
  180 : ([ /* sizeof() == 4 */
      "num" : 1,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 0,
          "off_lev" : 0,
          "area_level" : 2,
        ]),
      "level" : 3,
      "name" : "村长",
    ]),
  192 : ([ /* sizeof() == 4 */
      "num" : 3,
      "assign" : ([ /* sizeof() == 4 */
          "pos" : "area",
          "typ" : 1,
          "off_lev" : 1,
          "area_level" : 1,
        ]),
      "level" : 2,
      "name" : "随军",
    ]),
  1000 : ([ /* sizeof() == 3 */
      "num" : -1,
      "level" : 1,
      "name" : "闲职",
    ]),
])
